# Generated by Django 2.2 on 2019-12-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allproduct',
        ),
    ]
