# Generated by Django 2.2 on 2019-12-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_allproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=200)),
                ('expense_price', models.CharField(max_length=200)),
                ('expense_officer', models.CharField(max_length=200)),
            ],
        ),
    ]
