# Generated by Django 2.2 on 2019-12-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_contractus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractus',
            old_name='contract_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contractus',
            old_name='contract_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contractus',
            old_name='contract_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contractus',
            old_name='contract_subject',
            new_name='subject',
        ),
    ]
